### ISSUE TITLE
TagInput improvements

### ISSUE THREAD

**Issue by giladgray** [palantir/blueprint#1412]
Collecting a bunch of features I want to add to `TagInput`:

- [ ] 1. `inputValue`, `onInputChange` props to listen/control input without resorting to `inputProps`
- [x] 2. #1418 `placeholder` prop that is removed when `values.length > 0` (use `inputProps.placeholder` if you always want it there)
- [x] 3. `InputGroup` support for left icon / right element (needs styles) #1420
- [x] 4. #1418 `separator` prop automatically splits input value to add multiple values at once (default: `/,\s*/g`)
- [ ] 5. option to add values on `blur` (in addition to <kbd>enter</kbd>)
- [x] 6. #1418 `onChange` receives `string[]` and handles the add / remove array manipulation internally
- [x] 7. `disabled` support (needs styles) https://github.com/palantir/blueprint/pull/1819
- [x] 8. #1419 support for JSX `values`

**Comment by sushain97** [comment]
My #1408 is a dup of your # 3, feel free to close mine. Thanks again for the work on this, quite useful for us.

**Comment by JuoCode** [comment]
Provide a `suggestion list` to TagInput

**Comment by adidahiya** [comment]
@JuoCode I think that feature is covered by [MultiSelect](http://blueprintjs.com/docs/#labs.multiselect).

**Comment by JuoCode** [comment]
`MultiSelect` can only choose options from the dropdown list. What I want is the tag input like the [StackOverflow's ask question form](https://stackoverflow.com/questions/ask). It can let the user enter new tag or choose from the list.

**Comment by JuoCode** [comment]
Another problem is that `TagInput` must press enter to add new item, but this will also trigger submit if it's wrapped in a form.

**Comment by scottfr** [comment]
Any updates on (1) and (5)? They would both be quite helpful in improving the component.

**Comment by adidahiya** [comment]
I don't think there's any active work on the remaining items. Feel free to send a PR.

**Comment by marvinsum** [comment]
>  7. disabled support (needs styles)

This was added via #1819.
