### ISSUE TITLE
Follow-ups from build system refactor

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#1944]
flups from #1786

- [ ] Fix skipped table unit tests #1794 
- [ ] Enable `no-implicit-dependencies` lint rule
- [ ] ~~Bring [documentalist](https://github.com/palantir/documentalist/) into this repo (it's languishing out there on its own, unloved 😢)~~ nvm, gilad updated it
- [x] Switch test runner from phantomjs to headless Chrome
- [x] UMD bundle externals #1805 
- [x] import from `"sinon"` in a consistent way
- [x] use node-sass-chokidar (#1134)
- [ ] watch variant of `generate-docs-data`
