### ISSUE TITLE
Feature request: <DateRangeInput/>

### ISSUE THREAD

**Issue by neevany** [palantir/blueprint#249]
Same like `<DateInput/>` for DateRange , for now i used popover. but i think it is good to have it as a component

## TODOs

@cmslewis: I'll use this space to track TODOs for this component (currently living on `feature/date-range-input`).

### Part 9: Obey and control the focused field
- [x] The currently focused field dictates which end of the date range the next click will modify.
- [x] Move focus between fields intelligently after a date is selected.
- [x] Add unit tests to verify the behavior.

### Part 10: Basic documentation
- [x] Add documentation for `DateRangeInput`
    - [x] Basic description of the component (hovered range, selected range, typing, validation)
    - [x] Uncontrolled mode
    - [x] Controlled mode (add disclaimer that it isn't fully implemented yet)
    - [x] JavaScript API (props, etc. - can get this for free)
    - [x] Basic example with controls (at this point, mostly just need a `format` selector)

### Part 11: Merge `feature/date-range-input` into `master`
- [ ] Handle merge conflicts with @leebyp's changes from #575

### Eventually
- [ ] Add `allowSingleDayRange` prop
- [ ] Add `selectAllOnFocus` prop
- [ ] Show min/max dates as placeholder on focus in an empty field
- [ ] (e.g.) When selected range is `[<startDate>, <endDate>]` and end field is focused, clicking on `<startDate>` in calendar should _clear_ the start date and _leave_ the end date in place. (Currently, it clears the selected range and then sets the clicked date as a new end date.) Should work symmetrically for start field too.  
- [ ] More robust controlled mode (how should we handle hover events, if at all?)
- [ ] (Refactor) Pull date-range state-change logic into its own `DateRangeSelectionStrategy` class  

### Further out
- [ ] When focused in an input field, allow keyboard incrementing of each of the date, month, or year in isolation (similar to `TimeInput`).

**Comment by cmslewis** [comment]
Thanks for the nudge here, @neevany! We've built something like this on top of Blueprint here at Palantir before, but it definitely makes sense to have as a standalone component.

**Comment by giladgray** [comment]
Yes we've been planning to build such a thing for some time...
