### ISSUE TITLE
convert docs to Documentalist

### ISSUE THREAD

**Issue by giladgray** [palantir/blueprint#796]
Remaining tasks for the [documentalist](https://github.com/palantir/documentalist) conversion:

- [x] docs for other packages (only includes core here) #818 
- [x] all CSS markup examples are missing #813 
- [x] many React examples have borked styles #839 
- [x] fix overscroll issues #840 
- [x] syntax highlighting #846 
- [x] lingering `.kss-` class names #850 
- [x] `core/components/button.javascript-api` #882 
- [x] move some sections around #883 
- [x] handle `@Decorator` tag-like structures (`@HotkeysTarget`) #899
- [x] only show headings for active page #899 
- [x] bug on root page
- [ ] **update links!!**
- ~~update references in links (buttons.js => buttons.javascript-api) (#autolinking?)~~
  - ~~ok maybe support custom references to avoid ⬆️~~ 
- ~~render `@page` tags as links in the document?~~

Watch [`feature/documentalist`](https://github.com/palantir/blueprint/commits/feature/documentalist) for progress.

**Comment by giladgray** [comment]
shipped in [v1.14.0](https://github.com/palantir/blueprint/releases/tag/release-1.14.0)!
