### ISSUE TITLE
DateRangeInput improvements

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#805]
Would like to fix these remaining issues on `DateRangeInput`:

### P1
- [x] (e.g.) When selected range is `[<startDate>, <endDate>]` and end field is focused, clicking on `<startDate>` in calendar should _clear_ the start date and _leave_ the end date in place. (Currently, it clears the selected range and then sets the clicked date as a new end date.) Should work symmetrically for start field too.  **(See #856)**

### P2
- [x] Add `allowSingleDayRange` prop **(See #861)**
- [x] Add `selectAllOnFocus` prop **(See #858)**
- [x] (Refactor) Pull date-range state-change logic into its own `DateRangeSelectionStrategy` class **(See #880)**  

### P3
- [x] Show min/max dates as placeholder on focus in an empty field **(See #874)**
- [ ] More robust controlled mode (how should we handle hover events, if at all?)
- [ ] When focused in an input field, allow keyboard incrementing of each of the date, month, or year in isolation (similar to `TimeInput`).

### Maybe
- [x] Invoke all callbacks from `startInputProps` and `endInputProps` appropriately (e.g. `onFocus`, `onBlur`)

**Comment by cmslewis** [comment]
@giladgray @llorca I'm gonna squeeze this in for 1.13 to get it over with.

**Comment by llorca** [comment]
@cmslewis I'd add https://github.com/palantir/blueprint/issues/853 as a P1 -- it looks like every time you interact with the shortcuts, it then prevents any calendar navigation

**Comment by cmslewis** [comment]
@llorca just fixed issue #853 in PR #857. take a look.

**Comment by llorca** [comment]
This is pretty much done. I filed https://github.com/palantir/blueprint/issues/995 and https://github.com/palantir/blueprint/issues/996 to track the couple of P3s remaining 👍
